version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/app_db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=mysecretkey   #Update your secret key for JWT code generation
      - OPENAI_API_KEY=your-openai-api-key #Please update your open-ai-api-key
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user  #Please add your DB USER NAME and password
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
